name: Release

# Controls when the action will run.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
    environment: staging
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
          fetch-depth: 2
      # Runs a set of commands using the runners shell
      - name: Test git commit message
        run: |
          echo '### 1'
          echo $COMMIT_MSG
          echo '### 2'
          echo $(git log --format=%B -n 1 HEAD)
      # npx cut-release ${{ github.event.head_commit.message }}
