name: Release

# Controls when the action will run.
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
    environment: staging
    if: contains(github.event.head_commit.message, '[patch]') || contains(github.event.head_commit.message, '[minor]')
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Test git commit message
        run: |
          echo '### Get Type'
          echo $(git log --format=%B -n 1 HEAD | awk -F '[][]' '{print $2}')
